/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2022-12-07 00:48:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CadastroSucesso_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/npalmeira/InfoPosto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/infoposto/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/jsp/menu.jsp", Long.valueOf(1670336678434L));
    _jspx_dependants.put("jar:file:/C:/Users/npalmeira/InfoPosto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/infoposto/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1670336678441L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;  charset=UTF-8;");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"CSS/css-faleConosco/images/icons/favicon.ico\"/>\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-faleConosco/css/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-faleConosco/css/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-faleConosco/css/vendor/animate/animate.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-faleConosco/css/vendor/select2/select2.min.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-faleConosco/css/util.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-faleConosco/css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#div-msg {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("    padding: 90px 0;\r\n");
      out.write("	background: #EBF0F5;\r\n");
      out.write("}\r\n");
      out.write("#sucesso {\r\n");
      out.write("	color: #88B04B;\r\n");
      out.write("	font-family: \"Nunito Sans\", \"Helvetica Neue\", sans-serif;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	font-size: 40px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("p {\r\n");
      out.write("	color: #404F5E;\r\n");
      out.write("	font-family: \"Nunito Sans\", \"Helvetica Neue\", sans-serif;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("i {\r\n");
      out.write("	color: #9ABC66;\r\n");
      out.write("	font-size: 100px;\r\n");
      out.write("	line-height: 200px;\r\n");
      out.write("	margin-left: -15px;\r\n");
      out.write("}\r\n");
      out.write(".card {\r\n");
      out.write("	background: white;\r\n");
      out.write("	padding: 60px;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	box-shadow: 0 2px 3px #C8D0D8;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"IMG/images/icons/favicon.ico\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-formulariocadastro/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-formulariocadastro/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-formulariocadastro/vendor/animate/animate.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-formulariocadastro/vendor/select2/select2.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-formulariocadastro/css/util.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/css-formulariocadastro/css/main.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<div id=\"area-cabecalho\">\r\n");
      out.write("        <div id=\"area-logo\">\r\n");
      out.write("            <h1 href=\"/infoposto/web?action=HomeAction\">Info<span class=\"branco\">Posto</span></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"area-menu\">\r\n");
      out.write("            <a href=\"/infoposto/web?action=HomeAction\">Home</a>\r\n");
      out.write("            <a href=\"/infoposto/web?action=FrmBlogAction\">Blog</a>\r\n");
      out.write("            <a href=\"/infoposto/web?action=FrmFaleConosco\">Fale Conosco</a>\r\n");
      out.write("            <a href=\"/infoposto/web?action=FrmLoginAction\" style =\"float:right\">Login</a>\r\n");
      out.write("            <img src =\"IMG/user.png\"style=\"float:right;width:2vw\">\r\n");
      out.write("             \r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div id=\"div-msg\">\r\n");
      out.write("  <div id=\"main-container\">\r\n");
      out.write("	<div class=\"card\">\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"border-radius: 200px; height: 200px; width: 200px; background: #F8FAF5; margin: 0 auto; text-align: center\">\r\n");
      out.write("			<img src=\"https://cdn-icons-png.flaticon.com/512/1828/1828697.png\" height=\"200px\" ></img>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<h1 id=\"sucesso\">Sucesso</h1>\r\n");
      out.write("		<p style=\"font-size:25px;color:black;\">\r\n");
      out.write("			Cadastrado com sucesso!!!\r\n");
      out.write("		</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<footer>\r\n");
      out.write("			<div class=\"container-footer\">\r\n");
      out.write("				<div class=\"row-footer\">\r\n");
      out.write("					<!-- footer col-->\r\n");
      out.write("					<div class=\"footer-col\">\r\n");
      out.write("						<h4>Empresa</h4>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"\"> Quem somos </a></li>\r\n");
      out.write("							<li><a href=\"\"> Nossos serviços </a></li>\r\n");
      out.write("							<li><a href=\"\"> política de privacidade </a></li>\r\n");
      out.write("							<li><a href=\"\"> Nossos Parceiros</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--end footer col-->\r\n");
      out.write("					<!-- footer col-->\r\n");
      out.write("					<div class=\"footer-col\">\r\n");
      out.write("						<h4>Obter ajuda</h4>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">Fale Conosco</a></li>\r\n");
      out.write("							<li><a href=\"https://petrobras.com.br/pt/nossas-atividades/composicao-de-precos-de-venda-ao-consumidor/\">Entenda a politica de preço da Petrobrás</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-col\">\r\n");
      out.write("						<h4>Envie uma sugestão!</h4>\r\n");
      out.write("						<div class=\"form-sub\">\r\n");
      out.write("							<form>\r\n");
      out.write("								<input type=\"email\" placeholder=\"Digite aqui sua sugestão\" required>\r\n");
      out.write("								<button>Enviar</button>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("						<div class=\"medias-socias\">\r\n");
      out.write("							<a href=\"https://www.linkedin.com/login/pt\"><img src=\"img/linkedin.png.png\" alt=\"\"> </a>\r\n");
      out.write("							<a href=\"https://www.facebook.com/\"><img src=\"img/face.png.png\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("	\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
